# Generated by Django 3.0 on 2020-02-15 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ou_app', '0002_datanodedescriptor_descriptorcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformationinstance',
            name='transformation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ou_app.DataNodeDescriptor'),
        ),
    ]
